language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: nicksettje
  password:
    secure: ZPZsnXNwI3unCR6cLqHh6AJKIftiF3HPI7GDrPB12jT0VogkUveMyia3jEX4+3KIh1gzE0EVmGc4eeaDLq5t3vD3d2uvC2EHOGDFvKabSnryL12uPmsS0QBRqmcyV6CQSo3ZJ2wnG8UbqByzT+nv3OMIP8442NZFOgICaiJ7aHgIMtpriEpEKVSpkv3QUb068ANLe087ARqEB8+s6i2WUcZTCt1qxj+IJVEa6N2mwrGw7SPU0XUBQ/u/E+/FZmFbpp7LHVO4G+tOiGppOH5Z4BDCZqQOi/FURl8E8G74LF9G5UerWt1TLMrdKteMr7AVJ5w+oMy/CxPmz4zslufPS8yws+KctGHm3LKf7z2zos6oVZuc90eMWFvzR70J1iWeZov7EcMGRt62hu6E2PstPz0PuOODQy63cqU2Xo2uMNMm3YNteuWtjRQBSrIsxHfaPhHbCQ8L6NILK5rGTKQGzhMCDjKsdfIlahYIUhzA4Zxmbjx5BUkAZTUrK3NOyTYJux9fbNsWG+SCiEqDILiqDpbS0TA2VnNe3fR9e1WshWO0IDICMiWkHVgECNHKlyGCU23eyGF4uldXr6MNtTotPVOsRTT94vljR79QbEy5GqHaIHhgAlmnzXyO/GdU6ZnIP8SIcJPpbLLlmk4KjeHc7t8wThqGmFA88TPn5nn+aGw=
  on:
    tags: true
    repo: nicksettje/errs
    python: 3.7
